РАзные ресурсы по numpy
https://python-scripts.com/numpy
https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html
https://www.geeksforgeeks.org/how-to-calculate-the-determinant-of-a-matrix-using-numpy/


In [3]:
import numpy as np

In [18]:
A = np.array([1])
B = np.array([[1,1,1], [2,2,2]])
A - B # поэлементное вычитание матрицы

array([[ 0,  0,  0],
       [-1, -1, -1]])

In [19]:
A.shape # размер матрицы (2 столбца, 3 ряда)

(1,)

Умножение матриц только если кол-во столбцов равно строкам

In [5]:
A = np.array([[1,2], [4,5]])
B = np.array([[1,1], [2,2]])
A @ B

array([[ 5,  5],
       [14, 14]])

Перестановка аргументов не допустимо, результат будет разный

In [10]:
R = np.array([[1,2], [0, 3]])
L = np.array([[-1, 4], [-2, 5]])
R @ L

array([[-5, 14],
       [-6, 15]])

In [11]:
L @ R

array([[-1, 10],
       [-2, 11]])

Единичная матрица (это матрица у которой по диагонали идут единицы)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
B.dot(A)

array([[ 5,  7],
       [10, 14]])

Обратная матрица

In [28]:
A_inv = np.linalg.inv(A)

Декриминант

In [12]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

ЗАДАЧА

Задача с codewars
Matrix Determinant
https://www.codewars.com/kata/52a382ee44408cea2500074c/train/python

In [ ]:
# Одно из решений
def determinant(m):
    if len(m) == 1:
        return m[0][0]
    elif len(m) == 2:
        return m[0][0] * m[1][1] - m[0][1] * m[1][0]
    return sum(((-1) ** j) * v * determinant(minor(m, 0, j))
               for j, v in enumerate(m[0]))

    
def minor(m, x, y):
    return [[v for j, v in enumerate(row) if j != y]
            for i, row in enumerate(m) if i != x]    


In [ ]:
# Я пытался примерно так, но это первая задача с матрицами у меня. В итоге полез гуглить((((
import numpy as np

def determinant(a):
    return round(np.linalg.det(np.matrix(a)))